# Generated by Django 3.1.4 on 2020-12-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=50)),
                ('item_category', models.CharField(choices=[('food', 'FOOD'), ('dessert', 'DESSERT'), ('drink', 'DRINK')], default='food', max_length=20)),
            ],
            options={
                'verbose_name': 'Type',
            },
        ),
    ]
