# Generated by Django 3.1.4 on 2020-12-29 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_order_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amt_to_pay', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_ordered', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_orders_placed', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.ordercount'),
        ),
    ]
