# Generated by Django 3.1.4 on 2021-01-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20201229_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
