# Generated by Django 3.1.4 on 2020-12-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='item_type',
            field=models.CharField(choices=[('food', 'FOOD'), ('dessert', 'DESSERT'), ('drink', 'DRINK')], default='Food', max_length=8),
        ),
    ]
