# Generated by Django 3.1.4 on 2021-01-06 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reservations_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='name',
            new_name='experience_title',
        ),
        migrations.AddField(
            model_name='experience',
            name='experience_description',
            field=models.TextField(default='Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='shared_by',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.table'),
        ),
    ]
