# Generated by Django 3.1.4 on 2020-12-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_menu_ordered_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
